#!/bin/bash
echo -e {a,b,c,d,e,f,g,,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z}{a$'\n',b$'\n',c$'\n',d$'\n',e$'\n',f$'\n',g$'\n',h$'\n',i$'\n',j$'\n',k$'\n',l$'\n',m$'\n',n$'\n',p$'\n',q$'\n',r$'\n',s$'\n',t$'\n',u$'\n',v$'\n',w$'\n',x$'\n',y$'\n',z$'\n'}
